# Generated by Django 5.1.4 on 2025-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField()),
                ('copyright', models.TextField()),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
